First draft.
Add list and freeze commands.

diff --git a/bin/git-freeze b/bin/git-freeze
--- a/bin/git-freeze
+++ b/bin/git-freeze
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-OPTS_SPEC="\
+OPTIONS_SPEC="\
 freeze -l [-r <remote-name>]
 freeze -t [-r] [<remote-name>] <frozen-name>
 freeze -p [-a] [<remote-name>] [<frozen-name>]
@@ -21,7 +21,8 @@ t,thaw    thaw frozen ref into a branch
 p,push    push frozen ref to remote
 """
 
-eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
+SUBDIRECTORY_OK=1
+. "$(git --exec-path)/git-sh-setup"
 
 for arg; do
     case "$arg" in
@@ -39,9 +40,29 @@ for arg; do
 done
 
 if [ $LIST_COMMAND ]; then
-    git update-ref refs/f
+    echo "Frozen branches:"
+    git show-ref | \
+        cut -d' ' -f2 | \
+        sane_grep '^refs/freezer/' | \
+        sed -e 's|^refs/freezer/||'
 elif [ $THAW_COMMAND ]; then
     echo thaw
 elif [ $PUSH_COMMAND ]; then
     echo push
+else
+    BRANCH="$1"
+    if [ -z $1 ]; then
+        die "Branch name argument is required"
+    fi
+
+    BRANCH_REF=$(git show-ref --hash --heads "$BRANCH")
+    if [ $? -ne 0 ]; then
+        die "Branch does not exist: $BRANCH"
+    fi
+
+    echo Freezing branch: $BRANCH
+    git update-ref refs/freezer/$BRANCH $BRANCH_REF || \
+        die "Error: unable to update ref refs/freezer/$BRANCH $BRANCH_REF"
+    git branch -D $BRANCH 2>&1 > /dev/null || die "Unable to delete branch $BRANCH"
 fi
+
